var items = [
  'No formal Education',
  'Primary Education',
  'Secondary Education',
  'Vocational Qualification',
  "Bachelor's Degree",
  "Master's Degree",
  'Doctorate or Higher',
  'Diploma'
];
var villages = [
  "Ambewadi",
  "Antri Bk",
  "Antri Kh",
  "Ashta",
  "Arala",
  "Asvalwadi",
  "Aundhi",
  "Bambavade",
  "Beldarwadi",
  "Belewadi",
  "Beradewadi (N.V.)",
  "Bhairewadi",
  "Bhashtewadi (N.V.)",
  "Bhatshirgaon",
  "Bhatwadi",
  "Bilashi",
  "Biur",
  "Charan",
  "Chikhali",
  "Chikhalwadi",
  "Chinchewadi",
  "Chincholi",
  "Devwadi",
  "Dhamavade",
  "Dhaswadi",
  "Dholewadi",
  "Gavalewadi",
  "Ghagarewadi",
  "Girajvade",
  "Gudhe",
  "Hategaon",
  "Ingrul",
  "Jambhalewadi",
  "Kadamwadi",
  "Kalundre",
  "Kande",
  "Kandur",
  "Kapari",
  "Karamale",
  "Karanguli",
  "Kharale",
  "Khed",
  "Khirawade",
  "Khujgaon",
  "Khundalapur",
  "Kinarewadi",
  "Kokarud",
  "Kondaiwadi",
  "Kusaiwadi",
  "Kusalewadi",
  "Ladewadi",
  "Madalawadi",
  "Malewadi",
  "Manewadi",
  "Mangle",
  "Mangrul",
  "Mankarwadi (N.V.)",
  "Marathwadi",
  "Meni",
  "Mohare",
  "Morewadi",
  "Nathavade",
  "Natoli",
  "Nigadi",
  "Pachumbri",
  "Padali",
  "Padaliwadi",
  "Panchagani",
  "Panumbre Tarf Shirala",
  "Panumbre Tarf Warun",
  "Pavalewadi",
  "Phakirwadi",
  "Phuphere",
  "Punavat",
  "Ranjanwadi",
  "Red",
  "Rile",
  "Sagaon",
  "Sawantwadi",
  "Shendgewadi",
  "Shindewadi",
  "Shirala",
  "Shirala Kh.",
  "Shirsatwadi",
  "Shivarwadi",
  "Sirasi",
  "Sonavade",
  "Tadavale",
  "Takave",
  "Upavale",
  "Wadi Bhagai",
  "Wakurde Bk",
  "Wakurde Kh",
  "Yelapur",
  "Yeslewadi (N.V.)",
  "Ahirwadi",
  "Aitavade Bk",
  "Aitavade Kh",
  "Bagani",
  "Bahadurwadi",
  "Bahe",
  "Banewadi",
  "Bavchi",
  "Beradmachi",
  "Bhadkimbe",
  "Bharatwadi",
  "Bhatwadi",
  "Bhavaninagar",
  "Bichud",
  "Borgaon",
  "Chikurde",
  "Devarde",
  "Dhagewadi",
  "Dhavali",
  "Dhotrewadi",
  "Dongarwadi",
  "Dudhari",
  "Farnewadi(borgaon)",
  "Gatadwadi",
  "Gaundwadi",
  "Ghabakwadi",
  "Gotkhindi",
  "Hubalwadi",
  "Itakare",
  "Jakraiwadi",
  "Jambhulwadi",
  "June Khed",
  "Kakachiwadi",
  "Kalamwadi",
  "Kameri",
  "Kanegaon",
  "Kapuskhed",
  "Karandwadi",
  "Karanjvade",
  "Karve",
  "Kasegaon",
  "Kedarwadi",
  "Kharatwadi",
  "Kille Machhindra Gad",
  "Kole",
  "Konoli (N.V.)",
  "Koregaon",
  "Krishnanagar (N.V.)",
  "Kundalwadi",
  "Kurlap",
  "Ladegaon",
  "Lavanmachi",
  "Mahadevwadi",
  "Malewadi",
  "Manikwadi",
  "Maralnathpur",
  "Mardawadi",
  "Masuchiwadi",
  "Mirajwadi",
  "Nagaon",
  "Narsihapur",
  "Nave Khed",
  "Naykalwadi",
  "Nerle",
  "Ozarde",
  "Padavalwadi",
  "Peth",
  "Phalkewadi and Chandachiwadi",
  "Pharnewadi(shigaon)",
  "Pokharni",
  "Rethare Harnaksha",
  "Rethare Dharan",
  "Rozawadi",
  "Sakharale",
  "Satapewadi",
  "Shekharwadi",
  "Shene",
  "Shigaon",
  "Shirate",
  "Shirgaon",
  "Shivpuri",
  "Surul",
  "Takari",
  "Tambave",
  "Tandulwadi",
  "Thanapude",
  "Tujarpur",
  "Vashi",
  "Vitthalwadi",
  "Waghwadi",
  "Walwa",
  "Wategaon",
  "Yede Machchhindra",
  "Yede Nipani",
  "Yelur",
  "Yewalewadi",
  "Amanapur",
  "Ambak",
  "Andhali",
  "Ankalkhop",
  "Anugdewadi",
  "Asad",
  "Bambavade",
  "Bhilwadi",
  "Bramhanal",
  "Burli"
];

var busStand = [
  "Sangli",
  "Shirala",
  "Khanapur",
  "Atpadi",
  "Tasgaon",
  "Miraj",
  "Miraj_City Bus",
  "Kavathe-Mahankal",
  "Jat",
  "Vita",
  "Islampur",
  "Asta",
  "Kasegoan",
  "Palus",
  "Kudal",
  "Kadegao",
  "Khanapur"
];
